To organize better, renamed an ambiguous variable, and flesh out comments and reminders.
git-svn-id: https://tufte-latex.googlecode.com/svn/trunk@29 516e2f36-ce3a-0410-bea4-1d4a03f5df72

diff --git a/release b/release
--- a/release
+++ b/release
@@ -5,8 +5,11 @@ class='tufte-handout.cls'
 
 set -e # exit on first error
 
-if test $# -ne 1; then
-  echo "usage: $0 VERSION"
+# Verify prerequisites:
+
+if test $# -ne 1
+then
+  echo "Usage: $0 VERSION"
   exit 1
 fi
 
@@ -25,15 +28,6 @@ then
   exit 1
 fi
 
-date=`date +%Y/%m/%d`
-
-if ! grep -q $date $class
-then
-  echo "Error: date skew. '$date' does not match that in class"
-  grep -H ProvidesClass $class
-  exit 1
-fi 
-
 if ! grep -q $version History.txt
 then
   echo "Error: no release notes for '$version' found in History.txt"
@@ -41,7 +35,16 @@ then
   exit 1
 fi
 
-history_date=`date +%Y-%m-%d`
+class_date=`date +%Y/%m/%d` # (with slashes)
+
+if ! grep -q $class_date $class
+then
+  echo "Error: date skew. '$class_date' does not match that in class"
+  grep -H ProvidesClass $class
+  exit 1
+fi 
+
+history_date=`date +%Y-%m-%d` # (with dashes)
 
 if ! grep -q $history_date History.txt
 then
@@ -53,7 +56,7 @@ fi
 # Refresh sample document
 
 pdflatex sample-handout >  refresh-sample.log
-bibtex sample-handout   >> refresh-sample.log
+bibtex   sample-handout >> refresh-sample.log
 pdflatex sample-handout >> refresh-sample.log
 pdflatex sample-handout >> refresh-sample.log
 rm -f sample-handout.{aux,log,out} refresh-sample.log
@@ -68,13 +71,13 @@ cat << MESSAGE
 
 `openssl dgst -sha1 pkg/$package-$version.zip`
 
-Don't forget to tag (after committing changes),
+Don't forget to create an SVN tag (after committing changes),
 
  svn cp -m'To tag release $version.' \\
    https://$package.googlecode.com/svn/trunk \\
    https://$package.googlecode.com/svn/tags/rel_$version
 
-and upload,
+and upload the zip file,
 
  http://code.google.com/p/$package/downloads/list
  http://ctan.org/upload
